const actions = {
	SET_DATA: 'SET_DATA',
	ADD_WISHLIST: 'ADD_WISHLIST',
	LOG_USER: 'LOG_USER',
	ADD_COMPARE: 'ADD_COMPARE',
	REMOVE_COMPARE: 'REMOVE_COMPARE',
	REMOVE_ALL: 'REMOVE_ALL',
	ADD_PATH: 'ADD_PATH',
	COMPARE_LIST: 'COMPARE_LIST',
	SHOW_FAVED: 'SHOW_FAVED',
	REMOVE_FAVED: 'REMOVE_FAVED',
	UP_COMPARES: 'UP_COMPARES'
}

export default actions